### ISSUE TITLE
Ошибка для преобразования  MoneyToStr.percentToStr(16.188, RUS)

### ISSUE THREAD

**Issue by almirus** [javadev/moneytostr#18]
Добрый день!

java.lang.ArrayIndexOutOfBoundsException: 18 at
com.github.moneytostr.MoneyToStr.triad2Word(MoneyToStr.java:552) at
com.github.moneytostr.MoneyToStr.convert(MoneyToStr.java:514) at
com.github.moneytostr.MoneyToStr.percentToStr(MoneyToStr.java:431) at
com.github.moneytostr.MoneyToStr.percentToStr(MoneyToStr.java:391) at

**Comment by javadev** [comment]
Спасибо за ваше сообщение.

Я приготовил исправление https://github.com/javadev/moneytostr/pull/20
